[project]
name = "reasoning"
version = "0.1.0"
description = "Add your description here"
readme = "readme.txt"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.83",
    "datasets==4.6.1",
    "folium==0.16.0",
    "gdown>=6.1.0",
    "lightning>=2.6.5",
    "lm-eval>=0.4.12",
    "networkx==3.3",
    "omegaconf>=2.3.0",
    "osmnx==1.9.3",
    "scikit-learn>=1.9.0",
    "selenium>=4.48.0",
    "torch>=2.6.0",
    "transformers>=5.16.1",
    "trl>=0.29.1",
    "wandb>=0.29.0",
]
